### ISSUE TITLE
Would love to see more examples

### ISSUE THREAD

**Issue by steffanek** [antoine-coulon/effect-introduction#1]
Hi @antoine-coulon thanks for putting the work to create such a great intro on effect!
It was a great read and I believe it will help many devs around to start with Effect.
I really liked how you structured it and covered all the essential topics when it comes to coding.

To provide you with some feedbacks and perhaps improve comprehension for less experienced individuals (like me), I would have liked to see:
- More precision, on certain parts. As a reader, I really would like to see the drawbacks listed and detailed, so I can clearly see the problem and how effect address it. One example is the following: 

> Drawbacks of a Promise:
> Eagerly executed, hence is impure, referentially-opaque and is running computation (already a value).

It's hard to get a clear picture.

- Maybe a few more use cases - some more real-world examples, where it can be useful to use the resilience part.
In that section, you mentioned about `asyncInterrupt` - this might hard to grasp as well

> It allows us to model an acquire/release logic that is safe towards interruption and prevent memory leaks.

```
pipe(
  Effect.asyncInterrupt(() => {
    const timer = setInterval(() => {}, 1000);
    return Effect.sync(() => {
      clearInterval(timer);
    });
  }),
  Effect.fork,
  Effect.flatMap((fiber) => Fiber.interrupt(fiber))
);
```
- Btw, you could add links so the navigation could be quicker from the top to jump to each section (see screenshot below)

<img width="583" alt="links" src="https://github.com/antoine-coulon/effect-introduction/assets/22999414/8d87c92e-7108-49a8-bbc0-2d6fdcec6893">

Looking forward to the next part :)

**Comment by antoine-coulon** [comment]
Hey @steffanek, thanks a lot for you very complete feedback!

I'll try my best to make all those things clearer and more explicit (always the same problem) for sure. I'm also going to add more content into the TypeScript files and link them to their associated sections of the introduction, so that everyone can jump into more concrete examples if needed.

For the UI part, that's a good point, I'll make the navigation smoother 😄 

If you ever think about something else, feel free to add it there

Stay tuned!

**Comment by antoine-coulon** [comment]
Hey there @steffanek, hope you're doing well.

I just started the work on improvements you suggested. I'm also working on the TypeScript source files that will include examples for all sections with the latest versions of both `@effect/io` and `@effect/data`.

Everything should be dropped during the week

**Comment by antoine-coulon** [comment]
Hello @steffanek, just pushed changes I have been working on past week. Latest changes include more context, more explanations and more examples about the `#3 Resilience` chapter. Feel free to also check the associated TypeScript file which includes more examples than the markdown.

Let me know if everything is clearer for you.

**Comment by steffanek** [comment]
Hi @antoine-coulon looks really good. The read was very helpful to enhance the mental model!
Thanks again for that effort!

**Comment by antoine-coulon** [comment]
Hey @steffanek glad to hear that, thanks for your feedback! Don't hesitate to open other issues if ever some parts are still opaque or miss concrete examples
